services:
    ubuntu-system:
        # image: ubuntu:25.04
        container_name: ubuntu-system
        user: root
        working_dir: /mozart/
        build:
            context: .
            dockerfile: ubuntu-system.dockerfile
        volumes:
            - ../:/mozart/
            - ${HOME}:${HOME}
        command: >
            bash -c "
                cd /mozart/ &&
                mkdir -p build/ &&
                cd build/ &&
                cmake -DCMAKE_BUILD_TYPE=Release .. &&
                make &&
                make install &&
                cd /root/ &&
                bash
            "
        tty: true